name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-22.04 # https://github.com/swift-actions/setup-swift/issues/677
          - macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
    - name: Run tests
      run: swift test
  
